### ISSUE TITLE
VideoIsPrivate

### ISSUE THREAD

**Issue by ThatOneToast** [Mithronn/rusty_ytdl#45] opened 2024-10-06 21:02 UTC
All videos are publicly available and I am able to watch them without being signed in at all.

These are my options that I am downloading with.

```rust
let video_options = VideoOptions {
    quality: yt::VideoQuality::HighestAudio,
    request_options: yt::RequestOptions {
        proxy: Some(reqwest::Proxy::http("socks5://192.168.68.55:58358").unwrap()),
        max_retries: Some(3),
        ..Default::default()
    },
    ..Default::default()
};
```

It seems like 85-90% of the time I run into the `VideoIsPrivate` error even tho it's not. 
I have tried using different proxies in case that was an issue and no proxy at all, as well as routing all traffic. Sometimes we'll get a connection but then cancel at a 403 code, but then right again try to download you get a `VideoIsPrivate`.

**Comment by Mithronn** [comment] 2024-10-07 21:22
Duplicate of #39

**Closed by Mithronn** 2024-10-07 21:22 UTC
