### ISSUE TITLE
Package problems with rust-analyzer

### ISSUE THREAD

**Issue by CaptainKeys21** [Mithronn/rusty_ytdl#7] opened 2023-09-30 15:48 UTC
Hi! When I add the package in the Cargo.toml file, the rust-analyzer throw a error in the output log and stops working. The error goes away when I comment out the package in the Cargo.toml.

![image](https://github.com/Mithronn/rusty_ytdl/assets/89275202/a88da492-448b-4c02-ba9a-50095143cd8d)

I think it could be something in the dependencies.

**Comment by CaptainKeys21** [comment] 2023-10-08 20:32
I found out that I had some package not installed on my side, when I installed the rust-analyzer started to work again. But the error in the output still persists.

**Comment by Mithronn** [comment] 2023-10-08 20:51
@CaptainKeys21 thanks for the feedback. I just saw it and its seems the problem is releated with deno_ops crate. I will try to fix it in a few days / weeks

**Comment by Mithronn** [comment] 2023-11-13 14:50
I think this issue was fixed with the new release 0.6.5

**Closed by Mithronn** 2023-11-13 14:50 UTC
